/* Edit stages and projectFacts to update the story. A new project uses an existing board node and a stage position; no JSX edits needed. */
export const stages=[
{n:'00',label:'SYSTEM',at:0,title:'Farhan Islam',sub:'Electrical engineering / embedded systems / avionics',copy:'Electrical Engineering · Embedded Systems · Avionics. Scroll to enter the system.'},
{n:'01',label:'CONTROLLER',at:.13,title:'Inside the controller',sub:'CONTROL / MCU',copy:'Logic, timing and interfaces. The same questions come up in every embedded system: what is measured, what is controlled and what happens when an input is wrong?'},
{n:'02',label:'SIGNAL',at:.28,title:'Follow the signal',sub:'PIN → TRACE → CONVERSION',copy:'SENS → ADC → MCU. Watch one input become a digital reading, then reach the controller. The gold route is an illustration, not measured data.'},
{n:'03',label:'EXPERIENCE',at:.42,title:'Avionics / instrumentation',sub:'REACTION DYNAMICS · MAY–AUG 2026',copy:'Built a 20-channel LabJack T7 / Mux80 acquisition setup: ten pressure channels and ten thermocouple channels. Worked on measurement-chain correlation between shunt tap and LabJack readings.'},
{n:'04',label:'PROJECTS',at:.56,title:'Systems with a purpose',sub:'TWO PROJECTS / ONE TEST SYSTEM',copy:'A team course project, a personal spatial-mapping build and an avionics measurement chain. Follow the connections between them.'},
{n:'05',label:'SKILLS',at:.78,title:'Tools on the bench',sub:'COMPONENT NETWORK',copy:'Embedded C/C++, instrumentation and DAQ, hardware test, sensors, analog electronics, MATLAB, AutoCAD. Each belongs to a problem, not a buzzword list.'},
{n:'06',label:'ABOUT',at:.86,title:'The engineer',sub:'MCMASTER UNIVERSITY',copy:'Electrical Engineering co-op student, B.Eng expected April 2028. Avionics intern at Reaction Dynamics; McMaster Rocketry Club and Solar Car Electrical – Low Voltage team.'},
{n:'07',label:'CONTACT',at:.96,title:'Back to the whole system',sub:'CONTACT / RESUME',copy:'Interested in embedded hardware, instrumentation and test. The board connects the work; the person behind it is reachable below.'},
];
/* The case-study data and node map are editable without changing the 3D scene.
   Diagrams below are explanatory reconstructions, never photographs, measured traces,
   or drawings of a board Farhan designed. Numbers are used only where verified. */
export const projectFacts=[
{node:'CTRL',at:.57,type:'TEAM COURSE PROJECT · 1P13 · FEB–APR 2025',heading:'Accessible microwave control system',body:'Farhan contributed CAD/enclosure design and documentation to a team-built accessible microwave interface.',diagramTitle:'SENSE → ESP32 → AUDIO',architecture:[{name:'SENSE',detail:'Three HC-SR04 ultrasonic sensors, one per button column'},{name:'INTERPRET',detail:'ESP32 reads sensor distances and sends the selected button over WebSocket'},{name:'SPEAK',detail:'A local web client speaks the button label on a phone, with audio compatible with Bluetooth hearing aids'}],decisionTitle:'KEEP THE INTERFACE ON A PHONE',decision:'The team used a local web client and WebSocket updates to provide spoken feedback without a separate app download. An STM32 Nucleo supplied power to the ESP32 and sensors; it is not presented as the control MCU.',verificationTitle:'TEAM REPORT & FARHAN’S ROLE',verification:'Farhan’s role: CAD/enclosure design and documentation. The team describes a budget under $35, 90–95% accuracy and response time under 2500 ms. These are team-reported results, not independently validated metrics or Farhan’s individual claims. The signal diagram explains the team system, not a PCB Farhan designed.'},
{node:'SENS',at:.655,type:'PERSONAL BUILD',heading:'Indoor 3D spatial mapping',body:'A rotating time-of-flight sensor turns room measurements into a spatial representation.',diagramTitle:'DISTANCE → COORDINATES → CLOUD',architecture:[{name:'SCAN',detail:'VL53L1X time-of-flight sensor and stepper motor sweep the room'},{name:'CAPTURE',detail:'MSP432E401Y reads sensor distance over I²C at successive angles and layers'},{name:'MAP',detail:'Python / NumPy transform polar samples to Cartesian coordinates for Open3D point clouds'}],decisionTitle:'COORDINATES, NOT JUST DISTANCE',decision:'A rotating distance reading is only a range. Preserving its scan angle and layer lets the processing pipeline place each sample in three dimensions.',verificationTitle:'WHAT THE PROJECT SUMMARY SHOWS',verification:'The project summary identifies the MSP432E401Y, VL53L1X, motor and Python / NumPy / Open3D processing chain. The diagram reconstructs the data path; it is not actual scan data, a measured point cloud or independent validation of accuracy.',sourceLabel:'Project page',projectUrl:'https://fancy-brook-b6f.notion.site/MSP432-LiDAR-Room-Scanner-37344bb53cc9805f8890dedb5e257b23'},
{node:'DAQ',at:.70,type:'INTERNSHIP SYSTEM',heading:'Reaction Dynamics / DAQ',body:'A verified instrumentation contribution from Farhan’s internship, separate from the course and personal projects.',diagramTitle:'SENSORS → ACQUISITION → COMPARISON',architecture:[{name:'INPUT',detail:'Ten pressure channels and ten thermocouple channels'},{name:'ACQUIRE',detail:'20-channel LabJack T7 / Mux80 setup'},{name:'CHECK',detail:'Compare shunt-tap and LabJack signal-chain readings'}],decisionTitle:'TWO VIEWS OF A MEASUREMENT',decision:'Comparing shunt-tap and LabJack readings provides two views of the measurement chain. It helps check whether the acquisition path and the reference reading agree.',verificationTitle:'VERIFIED SCOPE',verification:'The verified scope is the 20-channel split and shunt-tap / LabJack correlation. No test values, rates, custom PCB design, control circuit or performance claims are inferred.',sourceLabel:'Verified internship facts'},
];
export const currentProject=(progress:number)=>[...projectFacts].reverse().find(p=>progress>=p.at-.015)||projectFacts[0];
export const skillFacts=[['MCU','Embedded C/C++'],['ADC','Instrumentation / DAQ'],['SENS','Sensor interfaces'],['ADC','Analog electronics'],['TEST','Hardware validation'],['CTRL','Controls / PID'],['COMMS','Interfaces'],['DAQ','LabJack T7 / Mux80']];
